#!/bin/sh
# Copyright (C) 2000-2020 Synology Inc. All rights reserved.

### This script will be executed when package installed and upgraded.
### Actions after package installed.
### ex. create database, create symbolic link...

if [ "$myradio1" = true ] ; then
    echo 'radio button 1 is selected' # the output log can be viewed at /var/log/packages/[packagename].log
fi

if [ "$myradio2" = true ] ; then
    echo 'radio button 2 is selected'
fi

exit 0
