language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
sudo: false
script: mkdir /tmp/n && ./configure $SSL_FLAG $LUA_FLAG --prefix=/tmp/n && make && make check && make install && /tmp/n/bin/nmap -A localhost

env:
  - SSL_FLAG="--without-openssl" LUA_FLAG="--without-liblua"
  - SSL_FLAG="" LUA_FLAG="--without-liblua"
  - SSL_FLAG="--without-openssl" LUA_FLAG=""
  - SSL_FLAG="" LUA_FLAG=""

notifications:
  irc:
    channels:
      - "chat.freenode.net#nmap"
    on_success: change
    on_failure: always
